extends:
  - "eslint:recommended"
  - "plugin:node/recommended"
plugins:
  - node
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
  semi:
    - error
    - always
  strict:
    - error
    - safe
